# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3b9d5fbd74e8831bb7f3d03e79d45dce569d03c6408a655e0380c19a2116b6f0286a4de7baad9598a6bb54bd5aa5fcc607b15644888bb30a13648ce2fe38fde

test:
  secret_key_base: 47c9a4ac231b8bf48bc6a779b4d4a663fbc655cb1135e1c04de0b680d7f7032cf4980359b964bc4994b66e446c30d88686fca6439448467ffba10c91e13e9845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
