# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2eb566436e68f47e2b21d700e5c586fe31d35ab169d6f1dd4f6d6f77802b2b997ebeee7871c06032635eaec396fae5d49b9fbcd3e2701abb40ce2a4bf613ead

test:
  secret_key_base: a41c433b2ad0b789e688051f7c81e8781e372b872fc8eb22451a60fa1a0ba94dabda523b820401f4e6405a539aa7d42980064d12e41d6d47fba965a5e10fb9b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
